src/objects/Backlog__c.object
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <label>Backlog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Backlogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tickets__c.object
<CustomObject>
    <fields>
        <fullName>Backlog__c</fullName>
        <label>Backlog</label>
        <referenceTo>Backlog__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sort_order__c</fullName>
        <label>Sort order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tickets</label>
    <nameField>
        <label>Tickets Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TheController.cls
@RestResource(urlMapping='/TheController/*')
global with sharing  class TheController
{    
@HttpGet
    global static list <Tickets__c> getTicketByID()
    {
       Id backId = ApexPages.CurrentPage().getParameters().get('id');
    RestRequest rep = RestContext.request;
    List <Tickets__c> result = [SELECT Id,Name,Sort_order__c FROM Tickets__c Where Backlog__c=:backId];
    return result;
    }
@HttpPost
    global static List <Tickets__c> createTickets(List<Tickets__c> Sort_order)
    {
     List <Tickets__c> updatearray= new list<Tickets__c>();
       for(Tickets__c t:Sort_order)
        { 
            Tickets__c tick = new Tickets__c(); 
            tick.Sort_order__c = t.Sort_order__c;
            updatearray.add(tick);
        }
    System.debug('Estoy entrando al metodo');
    update updatearray;
    return updatearray;
    }    
}