src/objects/Backlog__c.object
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <label>Backlog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Backlogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tickets__c.object
<CustomObject>
    <fields>
        <fullName>Backlog__c</fullName>
        <label>Backlog</label>
        <referenceTo>Backlog__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tickets</label>
    <nameField>
        <label>Tickets Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderTicketsFromProduct.cls
public class OrderTicketsFromProduct {
    public Backlog__c back;
    public OrderTicketsFromProduct(ApexPages.StandardSetController controller) {
    back = (Backlog__c ) controller.getRecord();
    }

   public List<Tickets__c> getBacklog (){
       List <Tickets__c> tick =[SELECT Id,Name FROM Tickets__c]; 
       return  tick;       
   }
    
    public void updateSortOrder() {
        String str = ApexPages.CurrentPage().getParameters().get('strSerialVal');
        system.debug('Serialized String = ' + str);
    }
    
    public PageReference processProjectTaskListBacklogUpdates() {
        
        return null;
    }
}