src/objects/Tickets__c.object
<CustomObject>
    <fields>
        <fullName>Sort_order__c</fullName>
        <label>Sort order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tickets</label>
    <nameField>
        <label>Tickets Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Order.cls
@RestResource(urlMapping='/Order/*')
global with sharing  class Order {
    global Order(){                
    }
    
@HttpGet
    global static Tickets__c getTicket()
    {
    RestRequest rep = RestContext.request;
    String TicketsID = rep.requestURI.substring(
                       rep.requestURI.lastIndexOf('/')+1);
    Tickets__c result = [SELECT Id,Name,Sort_order__c FROM Tickets__c ];
    return result;
     }
@HttpPost
    global static String createTickets(Double Sort_order)
    {
    Tickets__c t = new Tickets__c(Sort_order__c = Sort_order);
    update t;
    return t.Id;
    }    
}